### ISSUE TITLE
It crashed Sublime Text

### ISSUE THREAD

**Issue by MenatWorx** [Thom1729/Sublime-JS-Custom#3] opened 2018-01-15 20:48 UTC
After I installed your package, I could not use Sublime Text.  I tried several times , but it was unusable and hung.  I had to reinstall ST.  Your package may conflict with Sublime Tutor, as that name came up when I was trying to regain control.
Windows 8.1 64 bit, ST Build 3156 64 bit.

**Comment by Thom1729** [comment] 2018-01-15 20:52
I can confirm it's not supposed to do that.

Does the problem disappear if you disable Sublime Tutor? What other packages do you have installed?

**Comment by MenatWorx** [comment] 2018-01-16 01:35
No, it did not disappear after I removed Sublime Tutor.  The reason I mentioned Sublime Tutor was that the words "Sublime Tutor" appeared in the title bar of ST when I restarted ST after installing your package.  It did not reappear on subsequent restarts and I was not using it at the time.
I had to manually remove Sublime Tutor with Windows Explorer, as ST was unusable and had to be terminated abnormally.  I couldn't find your package to remove it, unless it was in installed packages, which I did not check.  I have many packages installed:
Ace Jump
AutoSetSyntax
Bound Keys
Bracket Highlighter
Color Picker
Color Highlighter
CSS3
ExportHTML
FindKeyConflicts
FindResultsBufferUtils
FTPSync
HTML5
LoremIpsum
Open In Browser
View in Browser
Override Audit
MultiEditUtils
Package Dev
Package Resource Viewer
Readme Please
RegReplace
Scope Hunter
Sidebar Tools
StatusBar Time
Sublime REPL
Terminal View
Theme - Eightlime

I may have missed a few.
I could be a memory allocation error.

**Comment by Thom1729** [comment] 2018-01-16 04:04
JS Custom will be installed in the Installed Packages directory. The compiled syntaxes will be placed in User/JS Custom.

Depending on your computer, compiling the sample syntaxes upon installation might take a few seconds, but certainly no more than ten seconds in total unless you're running on very slow hardware. I haven't tested it, but it now occurs to me that it could take longer if other syntaxes that depend on JavaScript need to be reprocessed by Sublime as well. This might include the core HTML syntax in the stable build. (The dev build introduces a new way of embedding one syntax in another that doesn't require as much processing.) My gut feeling is that this still couldn't take long enough that Sublime would seem to freeze, but I'll check it out.

Is there any output in the console?

**Comment by MenatWorx** [comment] 2018-01-16 14:01
>Is there any output in the console?
No. ST did not respond at all, and I waited at least 15 seconds several times.
ST was unusable, and and the screen faded.
Windows said, "Sublime Text is not responding - close program or wait?"
I chose to close the program and Windows said "Windows is searching for a solution to the problem".
If the package was compiling, I would expect to see some warning message, but there was nothing.

**Comment by dangh** [comment] 2018-01-17 01:38
I second that. After installed JS Custom, ST hangs even though I haven't selected it.
I'm using ST 3156 on macOS 10.13.3

**Comment by Thom1729** [comment] 2018-01-17 17:40
@dangh What packages do you have installed? Also, what hardware are you using?

@MenatWorx Could you post the exact list of installed packages from your `Package Control.sublime-settings` file?

When JS Custom is installed it does several things:

- Loads its own settings.
- Installs YAML Macros.
- Ensures that the ruamel-yaml dependency is in the path. (Package Control doesn't normally add newly installed dependencies to the path, so we have to do this ourselves.)
- Creates a directory under User to keep compiled syntaxes.
- Builds the example syntaxes.

I wonder if one of these steps is hanging. I've been focusing on the build step, which I suppose could take longer in pathological cases, but perhaps it's an earlier step. The next-most-likely culprit is installing YAML Macros. It *shouldn't* take even a second, but if there's a connectivity problem mid-installation I'm not sure what the failure mode would be.

**Comment by dangh** [comment] 2018-01-17 19:31
@Thom1729 I'm using MacBook Pro 2015 with latest macOS beta. This is my package control settings:

```json
{
	"bootstrapped": true,
	"ignore_vcs_packages": true,
	"in_process_packages":
	[
	],
	"install_prereleases":
	[
		"Package Control",
		"PackageDev",
		"GitGutter",
		"SublimeLinter"
	],
	"installed_packages":
	[
		"ActualVim",
		"AdvancedNewFile",
		"ApacheConf",
		"AutoItScript",
		"Awk",
		"ayu",
		"Babel Snippets",
		"Better CoffeeScript",
		"BetterFindBuffer",
		"BracketHighlighter",
		"Chain of Command",
		"Chrome Color Scheme",
		"CodeMap",
		"Color Highlighter",
		"ColorHelper",
		"ColorPicker",
		"Console Wrap",
		"CSS3",
		"DashDoc",
		"DocBlockr",
		"Dockerfile Syntax Highlighting",
		"Dotfiles Syntax Highlighting",
		"DoxyDoxygen",
		"EditorConfig",
		"Emmet",
		"Firebase Snippets",
		"Fix Mac Path",
		"Fold Comments",
		"FormatLua",
		"Generic Config",
		"Git Conflict Resolver",
		"GitGutter",
		"Handlebars",
		"Hjson",
		"HTML-CSS-JS Prettify",
		"INI",
		"Jade",
		"JavaScript Enhancements",
		"JavaScript Snippets",
		"JsPrettier",
		"LESS",
		"Lodash Completions",
		"LSP",
		"LuaExtended",
		"MagicPython",
		"MarkdownHighlighting",
		"Marked App Menu",
		"Material Theme",
		"Materialize",
		"NeoVintageous",
		"Package Control",
		"PackageDev",
		"PackageResourceViewer",
		"Phpcs",
		"Rust Enhanced",
		"ScopeHunter",
		"SCSS",
		"ShellScriptImproved",
		"Simple Import",
		"StandardFormat",
		"StandardSnippets",
		"Sublime Tutor",
		"sublime-javascript-snippets-standard",
		"sublime-reason",
		"SublimeLinter",
		"SublimeLinter-contrib-standard",
		"SublimeLinter-eslint",
		"SublimeLinter-flow",
		"SublimeLinter-lua",
		"SublimeLinter-php",
		"Sublimerge 3",
		"Swift",
		"Swig",
		"SyncedSideBar",
		"Syntax Highlighting for Sass",
		"TerminalView",
		"tern_for_sublime",
		"Theme - Monokai Pro",
		"ToggleQuotes",
		"Tomorrow Color Schemes",
		"TypeScript",
		"VimL"
	],
	"repositories":
	[
		"https://packagecontrol.io/prerelease/packages.json",
		"https://github.com/reasonml-editor/sublime-reason.git",
		"https://github.com/dangh/sublime-javascript-snippets-standard",
		"https://gist.githubusercontent.com/dangh/e93c66d046f0cabc18bb405b6bc02690/raw/5c25342b180a82e0bdb065be471d378dad278547/sublime-custom-repositories.json"
	]
}
```

Follow your explanation, I had managed to make it works. Steps below:
- Install JS Custom. ST hang.
- Check ST folder: ruame-yaml installed, but not YAML Macros.
- Disable JS Custom by editing User/Preferences.sublime-settings.
- Open ST again, install YAML via Package Control.
- Enable JS Custom.

**Comment by dangh** [comment] 2018-01-17 19:35
@Thom1729 I did test several cases:
1. Remove JS Custom but keep YAML Macros. Reinstall JS Custom and it work.
2. Keep JS Custom, remove YAML Macros. Restart ST and it hang again.

**Comment by Thom1729** [comment] 2018-01-17 20:01
Thanks. Package Control doesn't provide any way for one package to depend on another, so I had to roll my own. Apparently something's going wrong. I'll see if there's anything I can do to make the problem less likely to occur in the immediate term; in the medium term, I'll factor out the necessary YAML Macros code into a dependency to dodge the issue entirely.

**Comment by MenatWorx** [comment] 2018-01-18 01:02
@Thom1729 
Sorry, I completely uninstalled Sublime Text and all packages and settings, as I suspected a virus.
I did this after trying several times to get things to work,  I then re-installed Sublime Text and as many packages as I could remember (except yours).  Sublime Text (and Sublime Tutor) are now working fine.
I previously gave you a list of about 85% of the packages I use.
It could be that your package only conflicts with ST Build 3156.

**Comment by Thom1729** [comment] 2018-01-18 01:11
I'm running 3156 myself. As dangh mentions above, the problem seems to occur when JS Custom installs YAML Macros upon installation. He fixed the problem by installing YAML Macros directly via Package Control before installing JS Custom.

If the bug should recur, then you can remove JS Custom manually by removing the `JSCustom.sublime-package` file from your Installed Packages directory and removing `"JSCustom"` from your list of installed packages in your `Package Control.sublime-settings` file. It isn't necessary to uninstall Sublime, even if it's in a borked state.

I'm going to switch the dependency model ASAP; however, because there's a backlog for new Package Control packages and dependencies, it might be several days before the new dependency is in the system and I can release a build of JS Custom that uses it.

**Comment by MenatWorx** [comment] 2018-01-18 01:39
I violated my previous policy on new packages when I installed your package.  Before, I waited six months before I installed a newer package.  I shall now rigorously adhere to that policy.  As I mentioned, I couldn't find where your package was installed, and I panicked, not wishing to be exposed to a virus. Sublime Text would not run and I didn't know what else to do.  I don't know anything about YAML macros or how you use them.  This is the first time I have encountered a package that clobbered ST.

**Comment by Thom1729** [comment] 2018-01-18 03:19
Reopening the issue because it isn't resolved yet.

**Comment by Thom1729** [comment] 2018-01-18 03:21
Dependency is ready and awaiting a Package Control merge: https://github.com/wbond/package_control_channel/pull/6887

I also have a patch that may mitigate the issue. I'll push it out tomorrow after some more testing.

**Comment by Thom1729** [comment] 2018-01-29 22:18
The dependency is merged. Expect a fix for this issue sometime tomorrow.

**Closed** 2018-01-30 21:10 UTC
