### ISSUE TITLE
Improvement for styled-components / emotion

### ISSUE THREAD

**Issue by kud** [Thom1729/Sublime-JS-Custom#93] opened 2020-06-08 15:05 UTC
Hello Thom!

I've got some issues with css-in-js. See this picture:

![image](https://user-images.githubusercontent.com/655838/84046263-247e1a80-a9aa-11ea-8f6a-757af0e303f8.png)

Variables aren't coloured. Neither some nested styles.

Can I help in any way?

Thank you!

**Comment by wbond** [comment] 2020-06-08 15:08
You probably already know this, but from what I can tell the styled components use the file `Styled Components.tmLanguage` instead of `scope:source.css#rule-list-body` or something like that. It seems the styled components syntax is rather out-of-date.

**Comment by Thom1729** [comment] 2020-06-09 05:20
Yeah, I'm using the Styled Components syntax from the babel-sublime package specifically to provide a migration path for those users. I should probably update it to a more modern syntax if one exists and/or allow you to specify a custom Styled Components syntax definition in the JS Custom configuration.

**Comment by tsujp** [comment] 2020-06-20 05:45
In addition to this I've noticed that if you pass props to a styled component, or types, it breaks the syntax highlighting. See images below, the only difference is me removing the type `<IProps>`.

![broken with type](https://i.imgur.com/TzzCpNn.png)

![working without type](https://i.imgur.com/A1Li60h.png)

**Comment by Thom1729** [comment] 2020-06-25 19:39
The `<IProps>` thing will be addressed sooner or later as part of the TypeScript extension.

I sat down today to change the Styled Components extension so that you can specify your own third-party syntax for it, but I actually couldn't find a standalone Styled Components syntax. The only ones I found were from babel-sublime (used here) and Naomi. The structure of Naomi is a bit esoteric, so I'll have to take a look at whether I could make use of it.

Barring that, I suppose I'd have to improve it myself. I don't use Styled Components and have no immediate plans to, so I'd be effectively starting from scratch, and long-term maintenance might be a concern. Are the contents of the template string just a list of CSS rules, or is there extra syntax? Maybe I could get away with simply referring to a context in the core CSS syntax definition rather than a separate Styled Components syntax definition..

**Comment by tsujp** [comment] 2020-06-26 04:19
I'd have to double check but as a starting point you can put SCSS type styles and in addition to that JS/TS to extend functionality so it's a combination of both. Perhaps we could work on this together? I'd need guidance on how syntax highlighting etc works though as I have no idea but I am able and willing.

**Comment by wbond** [comment] 2020-06-26 10:33
@tsujp Is it SCSS, or just CSS? If you haven't already, reading https://www.sublimetext.com/docs/syntax.html#ver-dev will be a good place to start.

**Comment by kud** [comment] 2020-06-26 10:37
CSS-in-JS has nested declarations, and it's rather the same that SCSS.

**Comment by wbond** [comment] 2020-06-26 10:38
Ah, then reusing the CSS syntax won't be super useful at this moment.

**Comment by kud** [comment] 2020-06-26 10:42
A complex example:

```jsx
Timeline.Item.Bullet = styled.div`
  background: white;
  padding: 0.3rem;
  border-radius: 50px;
  width: 4rem;
  height: 4rem;
  cursor: pointer;
  display: flex;
  justify-content: center;
  align-items: center;

  transition: width 150ms ease, margin 150ms ease;

  ${({ state }) =>
    state === "start" &&
    css`
      margin-top: 1.6rem;
      margin-bottom: -1.6rem;
      width: 1rem;
      height: 1rem;
      cursor: initial;

      ${Timeline.Item.Bullet.Element.TextBox} {
        top: 10px;
      }

      ${Timeline.Item.Bullet.Element.Text} {
        transform: translateX(-10%);
      }
    `}

    ${({ state }) =>
      state === "end" &&
      css`
        margin-top: 1.6rem;
        margin-bottom: -1.6rem;
        width: 1rem;
        height: 1rem;
        cursor: initial;

        ${Timeline.Item.Bullet.Element.TextBox} {
          top: 10px;
        }

        ${Timeline.Item.Bullet.Element.Text} {
          transform: translateX(-90%);
        }
      `}

  ${({ isSelected }) =>
    isSelected &&
    css`
      width: auto;
      min-width: 100px;
    `}

  ${({ isSelected, state }) =>
    !isSelected &&
    !state &&
    css`
      &:hover {
        width: 6rem;
        margin-left: -1rem;
        margin-right: -1rem;
      }
    `}
`
```

**Comment by kud** [comment] 2020-06-26 10:43
This is the render with Naomi:

![image](https://user-images.githubusercontent.com/655838/85849108-a479f200-b7aa-11ea-971e-8ba7fb538794.png)

**Comment by kud** [comment] 2020-06-26 10:44
and with VS Code:

![image](https://user-images.githubusercontent.com/655838/85849143-b6f42b80-b7aa-11ea-94cc-77ff46006e24.png)

**Comment by wbond** [comment] 2020-06-26 11:36
It seems the styled components are immediately a rule list, but can also have custom selectors that don't exactly reflect CSS. From https://styled-components.com/docs/api#supported-css:

They have descendent selectors:

```
> p {
    text-decoration: underline;
}
```

Self-referential selectors:

```
&:hover {
    background: palevioletred;
}
```

Those can be combined with other selector chains:

```
html.test & {
    display: none;
}
```

But then media queries get thrown in:

```
@media (max-width: 600px) {
    background: tomato;
    &:hover {
        background: yellow;
    }
}
```

Of course there is the interpolated JS in there also.

My hunch is we can re-use the CSS rule-list-body, but then will have to do a little more work for the selectors since it supports a combination of custom selectors and `&`, plus media queries.

**Comment by Thom1729** [comment] 2021-06-25 16:13
@kud I've rewritten the Styled Components highlighting for the 4.1 beta. If you don't mind being on the bleeding edge, you can try that out and see if it works better for you. Feedback appreciated!

**Comment by kud** [comment] 2021-06-30 08:22
Hello @Thom1729 I'm sorry I don't use ST anymore. But thanks for notifying me about this. I'll try it if I come back to ST. 😊

**Comment by 2Pacalypse-** [comment] 2021-06-30 10:26
When's the plan to release the 4.1? I would like to test this, but messing about with installing beta releases manually seems like too much work ^^.

**Comment by Thom1729** [comment] 2021-06-30 14:06
I'd expect 4.1 within the next week or two. There's at least one minor feature I think needs adding. (Also, there's a temporary issue with the Package Control listing that needs to be ironed out.)

**Comment by Thom1729** [comment] 2021-07-01 16:34
FYI, now that the PC issue is fixed, you can try out the beta by simply adding the following to your Package Control settings:

```json
"install_prereleases":
[
    "JSCustom"
],
```

**Comment by 2Pacalypse-** [comment] 2021-07-02 12:51
I did that, but I didn't notice any difference, I think. Is there a way to easily see what's the current installed version and what specific styled-components changes would be most visible?

**Comment by Thom1729** [comment] 2021-07-02 15:30
This is how it should look in 4.0.6:

<img width="313" alt="JS-Custom-Styled-Before" src="https://user-images.githubusercontent.com/16958499/124297065-ab0f1800-db28-11eb-998b-55cf18e4a24a.png">

And in the beta:

<img width="307" alt="JS-Custom-Styled-After" src="https://user-images.githubusercontent.com/16958499/124297092-b06c6280-db28-11eb-81e5-94a36656a0f0.png">

**Comment by 2Pacalypse-** [comment] 2021-07-02 20:41
Yep, seems to work great!

A couple of weird use cases that I found that don't get styled properly, but it's completely fine even if they don't to me:

![image](https://user-images.githubusercontent.com/4757944/124326361-8184d980-db86-11eb-8745-2fca5da1d0a7.png)

![image](https://user-images.githubusercontent.com/4757944/124326392-8f3a5f00-db86-11eb-8c42-f52724bbcef6.png)

**Comment by Thom1729** [comment] 2021-07-02 22:32
Most of those look like bugs that can/should be fixed.

The second one — the template string inside the interpolation — is working as intended, and I don't think it would be practical or desirable to make have all template strings in interpolations follow their ‘parent’ template. However, the user could do something like configure `custom_templates.comments` to manually mark the inner template, e.g. ``/*styled*/`flex-grow: 1;` ``. At the moment, I don't think there's a good hook in the new Styled Components syntax definition for this, but I could add one.

**Comment by 2Pacalypse-** [comment] 2021-07-02 23:19
Yeah, I assumed the second one is working as intended.
>However, the user could do something like configure custom_templates.comments to manually mark the inner template, e.g. /*styled*/`flex-grow: 1;` . At the moment, I don't think there's a good hook in the new Styled Components syntax definition for this, but I could add one.

Eh, I wouldn't bother tbh. I'd feel pretty uneasy committing code that has some cryptic comments that are used to configure a particular text editor. Also, styled-components do have a [css](https://styled-components.com/docs/api#css) helper function which could be used here. And voila, you get perfect styling!

![image](https://user-images.githubusercontent.com/4757944/124335815-e26adc80-db9b-11eb-9fda-bbbbddadc898.png)

**Comment by Thom1729** [comment] 2021-11-01 16:59
Closing since the original issues should be fixed by now. Feel free to open new issues for any remaining bugs/missing features.

**Closed by Thom1729** 2021-11-01 16:59 UTC
